server:
  port: 8702 #服务消费方

#指定当前eureka客户端的注册地址

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8699/eureka,http://localhost:8698/eureka,http://localhost:8697/eureka #配置另外两台的端口
  instance:
    hostname: localhost

# 当前服务名称
spring:
  application:
    name: eureka-consumer
